FROM ghcr.io/puppeteer/puppeteer:latest

USER root

WORKDIR /server

COPY app .

COPY server.entrypoint.sh .

RUN npm ci

EXPOSE 3000

RUN chmod 777 ./data.txt

ENTRYPOINT ["sh", "./server.entrypoint.sh"]
